Warehouse/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Warehouse.Libraries.UsersManagement;
using Warehouse.Services;

namespace Warehouse.Controllers
{
    public class BranchController : Controller
    {
        private readonly IClientService _clientService;

        public BranchController(IClientService clientService)
        {
            _clientService = clientService;
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Index(int clientId)
        {
            var branches = _clientService.BranchesForClient(clientId);
            var branchesInfo = branches.Select(branch => new { branch.Id, branch.Name });
            return Json(branchesInfo.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

Warehouse/Areas/DocStore/Views/Shared/ClientBranchSelector.cshtml
@using System.Web.Mvc.Html

<div ng-controller="ClientBranchSelectorController" data-branch-path="@Url.Action("Index", "Branch", new {area = ""})" data-initial-selected-branch="@ViewData["SelectedBranch"]">
    @Html.DropDownList((string)ViewData["ClientFieldName"], (SelectList)ViewData["ClientList"], "Clients", htmlAttributes: new
   {
       @class = "form-control",
       @ng_model = "SelectedClient",
       @ng_change = "UpdateBranches()",
       @data_control_role = "ClientSelector",
       @style = "display: inline;",
       @data_val = "true",
       @data_val_required = "Owner is required"
   })

    @Html.DropDownList((string)ViewData["BranchFieldName"], Enumerable.Empty<SelectListItem>(), "Branches", htmlAttributes: new
   {
       @class = "form-control",
       @ng_model = "SelectedBranch",
       @ng_options = "branch as branch.Name for branch in Branches track by branch.Id",
       @ng_disabled = "SelectedClient == ''",
       @data_control_role = "BranchSelector",
       @style = "display: inline;"
   })

    @Html.ValidationMessage((string)ViewData["ClientFieldName"], new { @class = "text-danger", @style="display: block;" })
</div>