Warehouse/Areas/DocStore/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Warehouse.Areas.DocStore.Libs;
using Warehouse.Models;

namespace Warehouse.Areas.DocStore.Models
{
    public class Document : EntityBase
    {
        [Required]
        [AllowedValues(AllowedValues = "General,Client")]
        public string DocumentType { get; set; }

        [Required]
        public string Title { get; set; }
        public string Notes { get; set; }
        public bool Published { get; set; }
        
        public int? CategoryId { get; set; }
        public virtual Category Category { get; set; }

        public int? SubcategoryId { get; set; }
        public virtual Subcategory Subcategory { get; set; }
        
        [Required(ErrorMessage = "Attachment is required")]
        public int AttachmentId { get; set; }
        public virtual Attachment.Models.Attachment Attachment { get; set; }
    }
}

Warehouse/Areas/DocStore/Models/DocumentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Warehouse.Areas.DocStore.Models
{
    public enum DocumentTypes
    {
        General,
        Client
    }
}

Warehouse/Areas/DocStore/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using PagedList;
using Warehouse.Areas.Attachment.Services;
using Warehouse.Areas.DocStore.Models;
using Warehouse.Areas.DocStore.Services;
using Warehouse.Libraries.UsersManagement;
using Warehouse.Models;
using Warehouse.Services;
using AppContext = Warehouse.Libraries.AppContext;

namespace Warehouse.Areas.DocStore.Controllers
{
    [Authorize(Roles = ApplicationRole.Admin + "," + ApplicationRole.Client)]
    public class DocumentController : Controller
    {
        private readonly IDocumentService _documentService;
        private readonly ICategoryService _categoryService;
        private readonly IAttachmentService _attachmentService;
        private readonly IClientService _clientService;
        private readonly IClientDocumentOwnershipService _ownershipService;
        private readonly AppContext appContext;

        public DocumentController(AppContext appContext,
            IDocumentService documentService,
            ICategoryService categoryService,
            IAttachmentService attachmentService,
            IClientService clientService,
            IClientDocumentOwnershipService ownershipService)
        {
            _documentService = documentService;
            _categoryService = categoryService;
            _attachmentService = attachmentService;
            _clientService = clientService;
            _ownershipService = ownershipService;
            this.appContext = appContext;
        }

        private DocumentTypes DocumentType(string documentTypeId)
        {
            var documentType = (DocumentTypes)Enum.Parse(typeof(DocumentTypes), documentTypeId, true);
            return documentType;
        }

        public ActionResult Index(string documentTypeId, 
            string fileinfo, string filetype, 
            string category, string subcategory, 
            string client, string branch,
            string published, int? page)
        {
            Dictionary<string, string> searchCriteria = new Dictionary<string, string>();
            if (!string.IsNullOrWhiteSpace(fileinfo))
            {
                searchCriteria["fileinfo"] = fileinfo;
            }
            if (!string.IsNullOrWhiteSpace(filetype))
            {
                searchCriteria["filetype"] = filetype;
            }
            if (!string.IsNullOrWhiteSpace(published))
            {
                searchCriteria["published"] = published;
            }
            if (!string.IsNullOrWhiteSpace(category))
            {
                searchCriteria["category"] = category;
            }
            else //if category is not selected, deselect subcategory
            {
                subcategory = string.Empty;
            }
            if (!string.IsNullOrWhiteSpace(subcategory))
            {
                searchCriteria["subcategory"] = subcategory;
            }

            if (!appContext.IsCurrentUserAdmin)
            {
                client = appContext.CurrentUser.Client.Id.ToString();
            }
            if (!string.IsNullOrWhiteSpace(client))
            {
                searchCriteria["client"] = client;
            }
            else
            {
                branch = string.Empty;
            }
            if (!string.IsNullOrWhiteSpace(branch))
            {
                searchCriteria["branch"] = branch;
            }

            var documentType = DocumentType(documentTypeId);
            var documents = _documentService.Documents(documentType, searchCriteria);

            var pageNumber = page ?? 1;
            var pagedDocuments = documents.ToPagedList(pageNumber, PageSize);

            ViewBag.CurrentFilters = new Dictionary<string, string>()
            {
                { "fileinfo", fileinfo },
                { "filetype", filetype },
                { "published", published },
                { "category", category },
                { "subcategory", subcategory },
                { "client", client },
                { "branch", branch }
            };
            ViewBag.AvailableFiletypes = new SelectList(_documentService.DocumentFileFormats(documentType), filetype);
            ViewBag.PublishedStatuses = new SelectList(_documentService.DocumentPublishStatuses(), "Value", "Name", published);
            ViewBag.AvailableCategories = new SelectList(_categoryService.AllCategories(documentType), "Id", "Name", category);
            ViewBag.AvailableSubcategories = _categoryService.AllSubcategories(documentType);
            ViewBag.AvailableClients = new SelectList(_clientService.Clients(), "Id", "Name", client);
            if (!string.IsNullOrWhiteSpace(client))
            {
                ViewBag.AvailableBranches = new SelectList(_clientService.BranchesForClient(Convert.ToInt32(client)), "Id", "Name", branch);
            }
            else
            {
                ViewBag.AvailableBranches = new SelectList(Enumerable.Empty<Branch>());
            }
            
            var hiddenControls = appContext.IsCurrentUserAdmin ? new List<string>() : new List<string>() { "CreateDocument", "EditDocument", "PublishedStatus" };
            if (!(documentType == DocumentTypes.Client && appContext.IsCurrentUserAdmin))
            {
                hiddenControls.Add("SearchClient");
            }
            if (!(documentType == DocumentTypes.Client && (appContext.IsCurrentUserAdmin || appContext.IsCurrentUserClientManager)))
            {
                hiddenControls.Add("SearchBranch");
            }
            ViewBag.HiddenControls = hiddenControls;

            ViewBag.Title = $"{documentType} Documents";
            return View(pagedDocuments);
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult New(string documentTypeId)
        {
            var documentType = DocumentType(documentTypeId);
            PopulateCategories(documentType);
            if (documentType == DocumentTypes.Client)
            {
                PopulateClients();
            }
            return View();
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Create(string documentTypeId, int? ownerClientId, int? ownerBranchId,
            [Bind(Include = "Title, Notes, Published, CategoryId, SubcategoryId, AttachmentId")]Document document)
        {
            var documentType = DocumentType(documentTypeId);

            ClientDocumentOwnership documentOwnership = null;
            if (documentType == DocumentTypes.Client)
            {
                BuildClientDocumentOwnership(ownerClientId, ownerBranchId, out documentOwnership);
            }
            _documentService.CreateDocument(documentType, document, documentOwnership);
            _attachmentService.ConfirmAttachment(document.AttachmentId);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Edit(string documentTypeId, int id)
        {
            var documentType = DocumentType(documentTypeId);
            var document = _documentService.GetDocument(documentType, id);
            PopulateCategories(documentType, document.CategoryId);
            if (DocumentTypes.Client == documentType)
            {
                var ownership = _ownershipService.OwnershipForDocument(document.Id);
                if ("Branch" == ownership.OwnerType)
                {
                    PopulateClients(ownership.ClientId, Convert.ToInt32(ownership.OwnerId));
                }
                else
                {
                    PopulateClients(ownership.ClientId);
                }
            }
            return View("New", document);
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Update(string documentTypeId, int? ownerClientId, int? ownerBranchId, Document document)
        {
            var documentType = DocumentType(documentTypeId);
            var updatedFields = UpdatedFieldsFor(_documentFields);
            if (updatedFields.ContainsKey("AttachmentId"))
            {
                _attachmentService.ConfirmAttachment(Convert.ToInt32(updatedFields["AttachmentId"]));
            }
            ClientDocumentOwnership documentOwnership = null;
            if (documentType == DocumentTypes.Client)
            {
                BuildClientDocumentOwnership(ownerClientId, ownerBranchId, out documentOwnership);
            }
            _documentService.UpdateDocument(documentType, document, updatedFields, documentOwnership);

            var deletedAttachments = Request["DeletedAttachmentIds"];
            if (deletedAttachments != null)
            {
                var deletedAttachmentids = JsonConvert.DeserializeObject<int[]>(deletedAttachments);
                if (deletedAttachmentids != null)
                {
                    foreach (var attachmentId in deletedAttachmentids)
                    {
                        _attachmentService.DestroyAttachment(attachmentId);
                    }
                }
            }

            return Redirect(Request.UrlReferrer.PathAndQuery);
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Destroy(string documentTypeId, int id)
        {
            Document destroyedDocument;
            bool success = _documentService.Destroy(DocumentType(documentTypeId), id, out destroyedDocument);
            if (success)
            {
                _attachmentService.DestroyAttachment(destroyedDocument.AttachmentId);
                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        private void PopulateCategories(DocumentTypes documentType, int? selectedCategoryId = null)
        {

Warehouse/Areas/DocStore/Views/Document/Index.cshtml
@model PagedList.IPagedList<Warehouse.Areas.DocStore.Models.Document>
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    @if (!ViewBag.HiddenControls.Contains("CreateDocument"))
    {
        @Html.ActionLink("Create New Document", "New", "Document", new { @class = "btn btn-primary" })
    }
</div>
<div style="margin-top: 10px; margin-bottom: 10px;">
    @using (Html.BeginForm("Index", "Document", FormMethod.Get, new { @class = "form-inline" }))
    {
        <div class="row" style="margin-bottom: 10px;">
            <div class="col-lg-10">
                @Html.Editor("fileinfo", (string)@ViewBag.CurrentFilters["fileinfo"], new
           {
               htmlAttributes =
               new { @class = "form-control", @placeholder = "Search file", @style = "max-width: 100%;" }
           })
            </div>
            <div class="col-lg-2 text-right">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                @Html.ActionLink("Clear", "Index", "Document", new { area = "DocStore", pathPrefix = "" }, new { @class = "btn btn-default" })
            </div>
        </div>
        <div class="row">
            @*<div class="col-lg-3" style="margin-bottom: 10px;">
                    @Html.DropDownList("filetype", (SelectList)ViewBag.AvailableFiletypes, "All filetypes", new { @class = "form-control", @data_auto_post_form = "true" })
                </div>*@
            <div class="col-lg-3" style="margin-bottom: 10px;">
                @Html.DropDownList("category", (SelectList)ViewBag.AvailableCategories, "All categories", new
           {
               @class = "form-control",
               @data_widget_type = "WidgetCategorySelector",
               @data_subcategory_element_id = "subcategory",
               @data_all_subcategories_element_id = "allSubcategories",
               @data_auto_post_form = "true"
           })
            </div>
            <div class="col-lg-3" style="margin-bottom: 10px;">
                @Html.DropDownList("subcategory", Enumerable.Empty<SelectListItem>(), "All subcategories", new
           {
               @class = "form-control",
               @data_element_id = "subcategory",
               @data_auto_post_form = "true",
               @data_pre_selected = @ViewBag.CurrentFilters["subcategory"]
           })
            </div>
            @if (!ViewBag.HiddenControls.Contains("PublishedStatus"))
            {
                <div class="col-lg-3" style="margin-bottom: 10px;">
                    @Html.DropDownList("published", (SelectList)ViewBag.PublishedStatuses, "All statuses", new { @class = "form-control", @data_auto_post_form = "true" })
                </div>
            }
            @if (!ViewBag.HiddenControls.Contains("SearchClient"))
            {
                <div class="col-lg-3" style="margin-bottom: 10px;">
                    @Html.DropDownList("client", (SelectList)ViewBag.AvailableClients, "All Clients", new { @class = "form-control", @data_auto_post_form = "true" })
                </div>
            }
            @if (!ViewBag.HiddenControls.Contains("SearchBranch"))
            {
                <div class="col-lg-3" style="margin-bottom: 10px;">
                    @if (!((SelectList)ViewBag.AvailableBranches).Any())
                    {
                        @Html.DropDownList("branch", (SelectList)ViewBag.AvailableBranches, "All Branches", new
                   {
                       @class = "form-control",
                       @data_auto_post_form = "true",
                       @disabled = "true"
                   })
                    }
                    else
                    {
                        @Html.DropDownList("branch", (SelectList)ViewBag.AvailableBranches, "All Branches", new { @class = "form-control", @data_auto_post_form = "true" })
                    }
                </div>
            }
        </div>
    }

    <select class="hidden" data-element-id="allSubcategories">
        @foreach (var subcategory in ViewBag.AvailableSubcategories)
        {
            <option value="@subcategory.Id" data-parent-category="@subcategory.CategoryId">
                @subcategory.Name
            </option>
        }
    </select>
</div>

<table class="table documents-listing">
    <tr>
        @{var dummy = Model.FirstOrDefault(); }
        <th>
            @Html.DisplayName("Category")
        </th>
        <th>
            @Html.DisplayName("Subcategory")
        </th>
        <th>
            @Html.DisplayNameFor(model => dummy.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => dummy.Notes)
        </th>
        <th>
            @Html.DisplayName("Updated")
        </th>
        @if (!ViewBag.HiddenControls.Contains("PublishedStatus"))
        {
            <th>
                @Html.DisplayNameFor(model => dummy.Published)
            </th>
        }
        @if (!ViewBag.HiddenControls.Contains("EditDocument"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subcategory.Name)
            </td>
            <td>
                @Html.ActionLink(item.Title, "Show", "Attachment", routeValues: new { area = "Attachment", pathPrefix = "", id = item.AttachmentId }, htmlAttributes: null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            @if (!ViewBag.HiddenControls.Contains("PublishedStatus"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Published)
                </td>
            }
            @if (!ViewBag.HiddenControls.Contains("EditDocument"))
            {
                <td>
                    @{ var publishText = item.Published ? "Unpublish" : "Publish"; }
                    <div class="btn-group">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
                        <button class="btn btn-@(item.Published ? "info" : "warning")"
                                data-toggle="modal" data-target="#publish_confirm_@(item.Id)">
                            @publishText
                        </button>
                        <button class="btn btn-danger"
                                data-toggle="modal" data-target="#delete_alert_@(item.Id)">
                            Delete
                        </button>
                    </div>
                    <div class="modal fade" id="publish_confirm_@(item.Id)" tabindex="-1" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                @using (Html.BeginForm("Update", "Document", new { id = item.Id }, FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("_method", "put")
                                    @Html.Hidden("published", !item.Published)
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Confirm @publishText</h4>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure to @(publishText.ToLower()) document <strong>@(item.Title)</strong>?
                                    </div>
                                    <div class="modal-footer">
                                        <input type="submit" value="@publishText" class="btn btn-@(item.Published ? "info" : "warning")" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    @Html.Partial("~/Views/Shared/_DeleteConfirmation.cshtml", new ViewDataDictionary
                {
                    { "popupId", $"delete_alert_{item.Id}" },
                    { "itemId", item.Id },
                    { "itemName", item.Title },
                    { "controller", "Document" },
                    { "type", "document" }
                })
                </td>
                        }
        </tr>
                        }
</table>

<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    fileinfo = @ViewBag.CurrentFilters["fileinfo"],
    filetype = @ViewBag.CurrentFilters["filetype"],
    published = @ViewBag.CurrentFilters["published"],
    category = @ViewBag.CurrentFilters["category"],
    subcategory = @ViewBag.CurrentFilters["subcategory"],
    client = @ViewBag.CurrentFilters["client"],
    branch = @ViewBag.CurrentFilters["branch"]
}))
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DocStore")
}

Warehouse/Areas/DocStore/Views/Document/New.cshtml
@model Warehouse.Areas.DocStore.Models.Document

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Document</h2>

@using (Html.BeginForm(Model?.Id >= 0 ? "Update" : "Create", "Document"))
{
    @Html.AntiForgeryToken()
    if (Model?.Id >= 0)
    {
        @Html.Hidden("_method", "put")
    }

    <div class="form-horizontal">
        <h4>Document</h4>
        <hr />
        <div class="form-group">
            @Html.Label("FileUpload", "Select file", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Partial("~/Areas/Attachment/Views/Shared/AttachmentUpload.cshtml", new ViewDataDictionary
                {
                    { "id", "FileUpload" },
                    { "attachmentId", Model?.AttachmentId },
                    { "attachmentName", Model?.Attachment?.OriginalFilename }
                })
                @Html.HiddenFor(model => model.AttachmentId, new { require_validation = true })
                @Html.Hidden("DeletedAttachmentIds")
                @Html.ValidationMessageFor(model => model.AttachmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control", rows = 3 })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Published)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, null, "Select Category", htmlAttributes: new
           {
               @class = "form-control",
               @data_widget_type = "WidgetCategorySelector",
               @data_subcategory_element_id = "subcategory",
               @data_all_subcategories_element_id = "allSubcategories"
           })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubcategoryId, "Subcategory", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SubcategoryId, null, "Select Subcategory", htmlAttributes: new
           {
               @class = "form-control",
               @data_element_id = "subcategory",
               @data_pre_selected = @Model?.SubcategoryId
           })
                @Html.ValidationMessageFor(model => model.SubcategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.ClientList != null)
        {
            <div class="form-group">
                @Html.Label("OwnerClientId", "Owner", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Partial("~/Areas/DocStore/Views/Shared/ClientBranchSelector.cshtml", new ViewDataDictionary
                {
                    {"ClientFieldName", "OwnerClientId"},
                    {"BranchFieldName", "OwnerBranchId"},
                    {"ClientList", ViewBag.ClientList},
                    {"SelectedBranch", ViewBag.OwnerBranchId}
                })
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<select class="hidden" data-element-id="allSubcategories">
    @foreach (var subcategory in ViewBag.AllSubcategories)
    {
        <option value="@subcategory.Id" data-parent-category="@subcategory.CategoryId">
            @subcategory.Name
        </option>
    }
</select>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DocStore")
    @Scripts.Render("~/bundles/Attachment/Attachment")
}