Warehouse/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Warehouse.Models
{
    public class Branch : EntityBase
    {
        [Required]
        [Index("BranchUnique", 2, IsUnique = true)]
        [StringLength(300)]
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        [DataType(DataType.PostalCode)]
        public string PostCode { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string Telephone { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string Fax { get; set; }

        [Required]
        [Index("BranchUnique", 1, IsUnique = true)]
        public int ClientId { get; set; }
        public virtual Client Client { get; set; }

        public virtual ICollection<ApplicationUserBranch> ApplicationUserBranches { get; set; }
    }
}

Warehouse/Areas/Setting/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Warehouse.Libraries.UsersManagement;
using Warehouse.Models;
using Warehouse.Services;

namespace Warehouse.Areas.Setting.Controllers
{
    [Authorize(Roles = ApplicationRole.Admin)]
    public class BranchesController : Controller
    {
        private readonly IBranchService _branchService;
        private readonly IClientService _clientService;

        public BranchesController(IBranchService branchService, IClientService clientService)
        {
            _branchService = branchService;
            _clientService = clientService;
        }

        public ActionResult Show()
        {
            return RedirectToAction("Edit");
        }

        public ActionResult New(int clientId)
        {
            var client = _clientService.GetClient(clientId);
            SetClientInfo(clientId, client.Name);
            return View();
        }

        public ActionResult Create(int clientId, Branch branch)
        {
            _branchService.AddBranch(clientId, branch);
            return RedirectToAction("Show", "Clients", new { area = "Setting", id = clientId });
        }

        public ActionResult Edit(int id)
        {
            var branch = _branchService.GetBranch(id);
            SetClientInfo(branch.ClientId, branch.Client.Name);
            return View("New", branch);
        }

        public ActionResult Update(Branch branch)
        {
            _branchService.UpdateBranch(branch);
            return RedirectToAction("Show");
        }

        private void SetClientInfo(int clientId, string clientName)
        {
            ViewBag.clientId = clientId;
            ViewBag.clientName = clientName;
        }
    }
}

Warehouse/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Warehouse.Libraries.UsersManagement;
using Warehouse.Services;

namespace Warehouse.Controllers
{
    public class BranchController : Controller
    {
        private readonly IClientService _clientService;

        public BranchController(IClientService clientService)
        {
            _clientService = clientService;
        }

        [Authorize(Roles = ApplicationRole.Admin)]
        public ActionResult Index(int clientId)
        {
            var branches = _clientService.BranchesForClient(clientId);
            var branchesInfo = branches.Select(branch => new { branch.Id, branch.Name });
            return Json(branchesInfo.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

Warehouse/Areas/Setting/Views/Branches/New.cshtml
@model Warehouse.Models.Branch

@{
    ViewBag.Title = "New";
}

<h2>New</h2>


@using (Html.BeginForm(Model?.Id >= 0 ? "Update" : "Create", "Branches", new { clientId = ViewBag.clientId, id = Model?.Id }))
{
    @Html.AntiForgeryToken()
    if (Model?.Id >= 0)
    {
        @Html.Hidden("_method", "put")
    }

    <div class="form-horizontal">
        <h4>Branch for Client <strong>@ViewBag.clientName</strong></h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Client", "Show", "Clients", new { area = "Setting", id = ViewBag.clientId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}