Warehouse/Areas/DocStore/Models/Subcategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Warehouse.Models;

namespace Warehouse.Areas.DocStore.Models
{
    public class Subcategory : EntityBase
    {
        [Required]
        [StringLength(200)]
        [Index("SubcategoryUnique", 1, IsUnique = true)]
        public string Name { get; set; }

        [Required]
        [Index("SubcategoryUnique", 2, IsUnique = true)]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        
        public virtual ICollection<Document> Documents { get; set; }
    }
}

Warehouse/Areas/Setting/Controllers/SubcategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Warehouse.Areas.DocStore.Models;
using Warehouse.Areas.DocStore.Services;
using Warehouse.Libraries.UsersManagement;

namespace Warehouse.Areas.Setting.Controllers
{
    [Authorize(Roles = ApplicationRole.Admin)]
    public class SubcategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;

        public SubcategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Show()
        {
            return RedirectToAction("Edit");
        }

        public ActionResult New(int categoryId)
        {
            var category = _categoryService.GetCategory(categoryId);
            SetCategoryInfo(category.Id, category.Name);
            return View();
        }

        public ActionResult Create(int categoryId, Subcategory subcategory)
        {
            _categoryService.AddSubcategory(categoryId, subcategory);
            return RedirectToAction("Show", "Categories", new { area = "Setting", id = categoryId });
        }

        public ActionResult Edit(int id)
        {
            var subcategory = _categoryService.GetSubcategory(id);
            SetCategoryInfo(subcategory.CategoryId, subcategory.Category.Name);
            return View("New", subcategory);
        }

        public ActionResult Update(Subcategory subcategory)
        {
            _categoryService.UpdateSubcategory(subcategory);
            return RedirectToAction("Show");
        }

        private void SetCategoryInfo(int categoryId, string categoryName)
        {
            ViewBag.categoryId = categoryId;
            ViewBag.categoryName = categoryName;
        }
    }
}

Warehouse/Areas/Setting/Views/Subcategories/New.cshtml
@model Warehouse.Areas.DocStore.Models.Subcategory

@{
    ViewBag.Title = "New";
}

<h2>New</h2>


@using (Html.BeginForm(Model?.Id >= 0 ? "Update" : "Create", "Subcategories", new { categoryId = ViewBag.categoryId, id = Model?.Id }))
{
    @Html.AntiForgeryToken()
    if (Model?.Id >= 0)
    {
        @Html.Hidden("_method", "put")
    }

    <div class="form-horizontal">
        <h4>Subcategory for Category <strong>@ViewBag.categoryName</strong></h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Category", "Show", "Categories", new { area = "Setting", id = ViewBag.categoryId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}